### ISSUE TITLE
Need ahmed to come and work with us 

### ISSUE THREAD

**Issue by gharam37** [gharam37/a7lacomponent#2]
Come and Work now please ... and Assign me an issue ... and just as a punishment right a 100 line text file manually and commit it here ... Also you need to create a milestone so we would associate it with this issue ....

**Comment by ahmedadelbayoumi** [comment]
> i am writing 100 lines . 

 _- Ahmed Adel_

1. i am writing 100 lines .
2. i am writing 100 lines .
3. i am writing 100 lines .
4. i am writing 100 lines .
5. i am writing 100 lines .
6. i am writing 100 lines .
7. i am writing 100 lines .
8. i am writing 100 lines .
9. i am writing 100 lines .
10. i am writing 100 lines .
11. i am writing 100 lines .
12. i am writing 100 lines .
13. i am writing 100 lines .
14. i am writing 100 lines .
15. i am writing 100 lines .
16. i am writing 100 lines .
17. i am writing 100 lines .
18. i am writing 100 lines .
19. i am writing 100 lines .
20. i am writing 100 lines .
21. i am writing 100 lines .
22. i am writing 100 lines .
23. i am writing 100 lines .
24. i am writing 100 lines .
25. i am writing 100 lines .
26. i am writing 100 lines .
27. i am writing 100 lines .
28. i am writing 100 lines .
29. i am writing 100 lines .
30. i am writing 100 lines .
31. i am writing 100 lines .
32. i am writing 100 lines .
33. i am writing 100 lines .
34. i am writing 100 lines .
35. i am writing 100 lines .
36. i am writing 100 lines .
37. i am writing 100 lines .
38. i am writing 100 lines .
39. i am writing 100 lines .
40. i am writing 100 lines .
41. i am writing 100 lines .
42. i am writing 100 lines .
43. i am writing 100 lines .
44. i am writing 100 lines .
45. i am writing 100 lines .
46. i am writing 100 lines .
47. i am writing 100 lines .
48. i am writing 100 lines .
49. i am writing 100 lines .
50. i am writing 100 lines .
51. i am writing 100 lines .
52. i am writing 100 lines .
53. i am writing 100 lines .
54. i am writing 100 lines .
55. i am writing 100 lines .
56. i am writing 100 lines .
57. i am writing 100 lines .
58. i am writing 100 lines .
59. i am writing 100 lines .
60. i am writing 100 lines .
61. i am writing 100 lines .
62. i am writing 100 lines .
63. i am writing 100 lines .
64. i am writing 100 lines .
65. i am writing 100 lines .
66. i am writing 100 lines .
67. i am writing 100 lines .
68. i am writing 100 lines .
69. i am writing 100 lines .
70. i am writing 100 lines .
71. i am writing 100 lines .
72. i am writing 100 lines .
73. i am writing 100 lines .
74. i am writing 100 lines .
75. i am writing 100 lines .
76. i am writing 100 lines .
77. i am writing 100 lines .
78. i am writing 100 lines .
79. i am writing 100 lines .
80. i am writing 100 lines .
81. i am writing 100 lines .
82. i am writing 100 lines .
83. i am writing 100 lines .
84. i am writing 100 lines .
85. i am writing 100 lines .
86. i am writing 100 lines .
87. i am writing 100 lines .
88. i am writing 100 lines .
89. i am writing 100 lines .
90. i am writing 100 lines .
91. i am writing 100 lines .
92. i am writing 100 lines .
93. i am writing 100 lines .
94. i am writing 100 lines .
95. i am writing 100 lines .
96. i am writing 100 lines .
97. i am writing 100 lines .
98. i am writing 100 lines .
99. i am writing 100 lines .
100. i am writing 100 lines .
